<?php

/**
 * @file
 * Display Google Maps using the Embed API to remove billable usage.
 */

/**
 * Implements hook_theme().
 */
function google_map_embed_theme() {
  return [
    'google_map_embed' => [
      'variables' => [
        'attributes' => [],
        'place' => '',
      ],
    ],
  ];
}

/**
 * Prepares variables for Google Map embed templates.
 *
 * Default template: google-map-embed.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - attributes: The HTML attributes to apply to the iframe element.
 *   - place: place query string.
 */
function template_preprocess_google_map_embed(&$variables) {
  $api_key = \Drupal::service('settings')->get('google_map_embed_api_key');

  $variables['attributes']['frameborder'] = 0;
  $variables['attributes']['style'] = 'border:0';
  $variables['attributes']['src'] = "https://www.google.com/maps/embed/v1/place?q=$variables[place]&key=$api_key";
}
